name: Upload iOS App to App Store

on:
  push:
    branches:
      - main

jobs:
  upload:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    # 合并文件片段
    - name: Merge IPA parts
      run: |
        cat uploadtest/peaka.ipa.part* > uploadtest/peaka.ipa

    # 验证文件完整性
    - name: Verify file integrity
      run: |
        EXPECTED_MD5="ae939f46b9e1939381d8c3c3f717a7c7"
        ACTUAL_MD5=$(md5 -q uploadtest/peaka.ipa)
        
        if [ "$EXPECTED_MD5" != "$ACTUAL_MD5" ]; then
          echo "IPA file integrity check failed"
          exit 1
        fi

    # 上传到 App Store
    - name: Upload to App Store using altool
      env:
        IPA_PATH: "uploadtest/peaka.ipa"
        APPLE_ID: "zhengyanqin@sigmahongkong.shop"
        APP_SPECIFIC_PASSWORD: "hled-nmxe-rwol-occe"
      run: |
        xcrun altool --upload-app -f "$IPA_PATH" \
          -t ios \
          -u "$APPLE_ID" \
          -p "$APP_SPECIFIC_PASSWORD" \
          --verbose

